jobs:
  build:
    container:
      image: mcr.microsoft.com/openjdk/jdk:17-ubuntu
    name: Build and test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build test
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
name: pr-check
on:
  repository_dispatch:
    types: trigger-ga___pr-check.yml
